// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMa_m_wpoy-S9B9_NFS0TPMM0aDvmPjfE',
    appId: '1:986786867676:web:01637a4bcc5e1cadafc719',
    messagingSenderId: '986786867676',
    projectId: 'campuspulse-3b254',
    authDomain: 'campuspulse-3b254.firebaseapp.com',
    storageBucket: 'campuspulse-3b254.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvePITJfMOR1YcmF8IAVKpNs8RKzykzpQ',
    appId: '1:986786867676:android:ff277bbe53523b82afc719',
    messagingSenderId: '986786867676',
    projectId: 'campuspulse-3b254',
    storageBucket: 'campuspulse-3b254.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd_Ci_F3gA6Huq0K2_OAjIlTD7_NjzYqU',
    appId: '1:986786867676:ios:1a3effb16de9b494afc719',
    messagingSenderId: '986786867676',
    projectId: 'campuspulse-3b254',
    storageBucket: 'campuspulse-3b254.firebasestorage.app',
    iosBundleId: 'com.example.campuspulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd_Ci_F3gA6Huq0K2_OAjIlTD7_NjzYqU',
    appId: '1:986786867676:ios:1a3effb16de9b494afc719',
    messagingSenderId: '986786867676',
    projectId: 'campuspulse-3b254',
    storageBucket: 'campuspulse-3b254.firebasestorage.app',
    iosBundleId: 'com.example.campuspulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMa_m_wpoy-S9B9_NFS0TPMM0aDvmPjfE',
    appId: '1:986786867676:web:f18f028ddc77f91eafc719',
    messagingSenderId: '986786867676',
    projectId: 'campuspulse-3b254',
    authDomain: 'campuspulse-3b254.firebaseapp.com',
    storageBucket: 'campuspulse-3b254.firebasestorage.app',
  );

}